import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/thumbail">Thumbail</Link>
        </li>
        <li>
          <Link to="/styleguide">StyleGuide</Link>
        </li>
        <li>
          <Link to="/blogsingle">BlogSingle</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/abouttheauthor">AbouttheAuthor</Link>
        </li>
        <li>
          <Link to="/store">Store</Link>
        </li>
        <li>
          <Link to="/singleproduct">SingleProduct</Link>
        </li>
        <li>
          <Link to="/singleproductone">SingleProductOne</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/passwordprotected">PasswordProtected</Link>
        </li>
        <li>
          <Link to="/licenses">Licenses</Link>
        </li>
        <li>
          <Link to="/changelog">Changelog</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
